version: "3"

services:

  keycloak-db:
    image: "postgres:12.3-alpine"
    networks:
      - "keycloak-net"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

  keycloak:
    image: "jboss/keycloak:10.0.1"
    networks:
      - "keycloak-net"
    expose: 
      - "8080"
    depends_on:
      - "keycloak-db"
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_FRONTEND_URL: "http://localhost:8080/auth"
      DB_VENDOR: "postgres"
      DB_ADDR: "keycloak-db"
      DB_PORT: 5432
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    # volumes:
    #   - ./setup.sh:/opt/jboss/startup-scripts/setup.sh
    restart: "on-failure"

  keycloak-lb:
    image: "nginx:1.18.0-alpine"
    networks: 
      - "keycloak-net"
    ports: 
      - "8080:80"
    depends_on: 
      - "keycloak"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: "on-failure"

networks:
  keycloak-net:

volumes:
  keycloak-db:
