version: "3"

services:

  mysql:
    image: "mysql:5.7.30"
    networks:
      - "mysql-net"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

networks:
  mysql-net:

volumes:
  mysql-data:
